[linux_servers]
linux-ec2 ansible_host=172.31.21.152 ansible_user=ec2-user ansible_ssh_private_key_file=~/venterra.pem

[windows_servers]
windows-ec2 ansible_host=172.31.16.77

[windows_servers:vars]
ansible_user=Administrator
ansible_password=UE%Y?FzahUFoWAi*1%SuD(NC!(a%XCyw
ansible_connection=winrm
ansible_port=5985
ansible_winrm_scheme=http
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore
